sudo: required

services:
  - docker

language: bash

before_install:
  - sudo docker pull centos:centos6

install:
  - sudo docker run -d --name centos6 centos:centos6 sleep 120
  - sudo docker ps -a

script:
  - sudo docker exec centos6 cat /etc/issue
  - sudo docker exec centos6 ls -l
  - sudo docker exec centos6 pwd
  - sudo docker exec centos6 df -h
  - sudo docker exec centos6 find -name hello.sh

after_script:
  - sudo docker stop centos6
