sudo: required

env:
  - WORKSPACE='/project'

services:
  - docker

language: bash

before_install:
  - sudo docker pull knowshan/centos7-mkrpm

install:
  - sudo docker run -d -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name centos knowshan/centos7-mkrpm
  - sudo docker exec centos rpmdev-setuptree

script:
  - sudo docker exec centos mkrpm

after_script:
  - sudo docker stop centos

before_deploy:
  - find ./ -ls
  - env

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: HFe9dqJCLnJauR2q4vaOm5PgJcfpRyVBRL+7XkM/Y/e9rYx6TeJdVv6zDpvFIhC14ixgD+s+xy9XgZROdbwg7lLGU6wHywxTAj0iEDH6L4kTwrpU/SHmJ8VMyWuZfl3uh/bY32WpZlUQvuGKW2bw4vM3wlKg6Nrq0Jr2A6MimTD2PYDwO0v7KIcy0txaPpS4bNN/3rzKu3ThRhwN1omgb0114ifx0O4f7lxKZ1CBTkQCCyh6VzgN3gl/vDzpNSpMxsBcM+LPPKbRLqIT5KRc+cPcE6sv9KhDF4pXQ/3T7L28bX7tLFqciZc3DwNAefG1TOoLysRseXjV6dVBkLEBv+yJWilSeHg/8Af2PVkRnM97DNLsAkpomrNjgbillR6KYieGTlUOsKJmOk1OMGLtnpGGo/A8ICJOkX/Wn7o74QNOZ3xOE9qP0AQ3sxonQhM6u38y1hzeTbT9pFSztXacwvczatz5ajs1QtGZIb3tB4n/mVVmjZ2DX5t7lPnqC+Yveq0gT2DWRXwgSQNZUHBB4SPcR+aiYzNBNR5jsXhpCrho7BLtxBy8vnT0BCcxFdbG0Pu5vTYX/TikNCOSEadEawDu8nlFRlLwNMG+6ySsCFl1ewv6grsZ8f0U4ip4WkbRg9meJzUo41epkpSUmcs/+oQqb8wM3Nit+mvUBJ/m6yM=
  file: "$PWD/*.md"
  on:
    repo: knowshan/junglegym
    tags: false
