sudo: required

env:
  - WORKSPACE='/project'

services:
  - docker

language: bash

before_install:
  - sudo docker pull knowshan/centos-buildsys

install:
  - sudo docker run -d -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name centos knowshan/centos7-mkrpm
  - sudo docker exec centos rpmdev-setuptree

script:
  - sudo docker exec centos "$WORKSPACE"/mkrpm.sh -p "${TRAVIS_REPO_SLUG}"

after_script:
  - sudo docker stop centos

