sudo: required

env:
  - PROJECT='/project'

services:
  - docker

language: bash

before_install:
  - sudo docker pull centos:centos6

install:
  - sudo docker run -d -it -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -v $PWD:${PROJECT} --name centos6 centos:centos6
  - sudo docker ps -a

script:
  - ls -l
  - find
  - env
  - sudo docker exec centos6 env
  - sudo docker exec centos6 /project/src/hello.sh 'Hello World!'

after_script:
  - sudo docker stop centos6

